### Local test - Root route
GET http://localhost:8080/

### Local test - All contacts
GET http://localhost:8080/contacts

### Local test - One contact
GET http://localhost:8080/contacts/6906df468c0abc46e3e19583

### Local test - Professional route
GET http://localhost:8080/professional


### Render test - Root route
GET https://cse-341-w01-contacts.onrender.com/

### Render test - All contacts
GET https://cse-341-w01-contacts.onrender.com/contacts

### Render test - One contact
GET https://cse-341-w01-contacts.onrender.com/contacts/6906df5e8c0abc46e3e19584

### Render test - Professional route
GET https://cse-341-w01-contacts.onrender.com/professional

### Render test - New contact (POST)
POST https://cse-341-w01-contacts.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Donny",
  "lastName": "Doe",
  "email": "jane.doe@example.com",
  "favoriteColor": "Navy",
  "birthday": "1998-05-20"
}


### Render test - Update existing contact (PUT - John Doe)
PUT https://cse-341-w01-contacts.onrender.com/contacts/690d80759c1acdc01132783c
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@updatedexample.com",
  "favoriteColor": "Blue",
  "birthday": "1990-03-15"
}


### Render test - Delete contact (DELETE - Jane Doe)
DELETE https://cse-341-w01-contacts.onrender.com/contacts/690d7f9c9c1acdc01132783b


### Render test - Verify deleted contact (GET)
GET https://cse-341-w01-contacts.onrender.com/contacts/690d7f9c9c1acdc01132783b

